### PR TITLE
Relaxed version checking for binaries

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The Python bindings require a strict version of the binaries. We should relax this and instead use the binaries version as a minimum version.

### CODE REVIEW

**Comment by dtip** [comment]
At least the linter is having a productive quarantine!

**Comment by iainrussell** [comment]
@conda-forge-admin, please rerender

**Comment by iainrussell** [comment]
Yes @dtip !  :)

**Comment by iainrussell** [comment]
@conda-forge-admin, please restart ci

**Comment by iainrussell** [comment]
Thanks @shahramn !

**Pull request merged**
