### PR TITLE
Update to version 2.10.0 and try python3

### PR DESCRIPTION
**Pull request by StephanSiemen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@StephanSiemen The eccodes 2.10.0 package isn't found yet, might be related to the conda-forge mirror. And we need to get the python matrix working. A rerender didn't work, so we might have to do this by hand. @ocefpaf Any hints?

**Comment by kmuehlbauer** [comment]
see in the other PR #41

**Comment by StephanSiemen** [comment]
@kmuehlbauer, should I close this PR and concentrate on #41?

**Comment by kmuehlbauer** [comment]
@StephanSiemen The good thing on the other PR is that all maintainers can push to the bot's branch.

**Comment by kmuehlbauer** [comment]
Yes, we can close this one here.

**Pull request closed without merging**
