### PR TITLE
WIP: Update Pinnings and test for py3k

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This is a follow up to https://github.com/conda-forge/eccodes-feedstock/pull/25

Do not merge!

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf  The log doesn't contain the error message. IIRC there is some strategy to get hold of the whole log. Could you hint me there?

**Comment by ocefpaf** [comment]
> @ocefpaf The log doesn't contain the error message

You can try something like this: https://github.com/conda-forge/libgd-feedstock/blob/master/recipe/build.sh#L7

**Comment by kynan** [comment]
@kmuehlbauer How about [SSHing into the build machine](https://circleci.com/docs/ssh-build/)?

**Comment by kmuehlbauer** [comment]
@kynan Worth a try. Anyway, can you have a look at the failing Travis builds, are the python bindings python3 ready?

**Comment by kynan** [comment]
@kmuehlbauer Nope, the Python bindings in ecCodes 2.1.0 are not Python 3 ready yet, but @shahramn and @erget are [working on it](https://software.ecmwf.int/issues/browse/SUP-1419).

**Comment by kynan** [comment]
@kmuehlbauer Not sure what's going wrong, but I suspect it's related to the extension module being built as `_gribapi_swig.cpython-35m-darwin.so`. Not a Mac user though, so I don't have any experience building Python extension modules on the Mac...

**Comment by kmuehlbauer** [comment]
@kynan I'll try this at home, em locally, to find the culprit. It's obviously py3k related. Closing this.

**Comment by kynan** [comment]
@kmuehlbauer Thanks, keep us posted how you get along.

**Pull request closed without merging**
