### PR TITLE
Version 2.3.0

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ocefpaf Although travis reports green, all builds have been terminated due to log-length according to the logs. This is also indicated by the short build times.

We need to implement those log-length fixes of yours. I can do this monday earliest.

**Comment by ocefpaf** [comment]
Probably. I can't look at the logs now (I'll on mobile most of the day. )

On Jun 10, 2017 3:28 AM, "Kai Mühlbauer" <notifications@github.com> wrote:

@ocefpaf <https://github.com/ocefpaf> Although travis reports green, all
builds have been terminated due to log-length according to the logs. This
is also indicated by the short build times.

We need to implement those log-length fixes of yours. I can do this monday
earliest.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/python-eccodes-feedstock/pull/21#issuecomment-307546301>,
or mute the thread

**Comment by kynan** [comment]
@kmuehlbauer the tests had already passed, the log stops somewhere in rewriting rpaths. This shouldn't prevent merging this, should it?

**Comment by ocefpaf** [comment]
The binary upload happens after that. The green CI there is misleading. We
should not merge b/c that won't create the new version package.

On Jun 10, 2017 4:12 PM, "Florian Rathgeber" <notifications@github.com>
wrote:

@kmuehlbauer <https://github.com/kmuehlbauer> the tests had already passed,
the log stops somewhere in rewriting rpaths. This shouldn't prevent merging
this, should it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/python-eccodes-feedstock/pull/21#issuecomment-307584682>,
or mute the thread

**Comment by kynan** [comment]
Why would it not?

**Comment by kmuehlbauer** [comment]
> Why would it not?

The section where the actual upload takes place wasn't run at all. So it seems from the log output. Let's see how the build does with the reduced log output.

**Comment by kmuehlbauer** [comment]
Now this worked just fine. Merging.

**Comment by ocefpaf** [comment]
Thanks for fixing it Kai!

**Pull request merged**
